### ISSUE TITLE
Some layouts

### ISSUE THREAD

**Issue by Tavousi** [hapijs/visionary#16]
Hi, i need to use define 2 layout in my app but i cant add more than one layout like this 

```
            plugin: {
                register: 'visionary',
                options: {
                    engines: { html: 'handlebars' },
                    path: './client/web',
                    layout: true,
                    layoutPath: './client/web',
                }
            }
```

i have some pages in my app , they have different layout !?

**Comment by jedireza** [comment]
Thanks for opening an issue.

This purpose of `visionary`) is to configure a views engine when using rejoice (the hapi CLI) or glue.

[`vision`](https://github.com/hapijs/vision) is the actual template rendering plugin and I don't think it supports multiple layouts. You can however override the default options, checkout the API docs:

 - https://github.com/hapijs/vision/blob/master/API.md
