### ISSUE TITLE
Deprecate?

### ISSUE THREAD

**Issue by hueniverse** [hapijs/visionary#17]
Anyone using this module?

**Comment by jedireza** [comment]
Yep, there's activity:

<img width="354" alt="screen shot 2017-11-03 at 5 50 12 pm" src="https://user-images.githubusercontent.com/979929/32400622-b21e398c-c0bf-11e7-8d27-7c37a29b1daf.png">

_Via: https://www.npmjs.com/package/visionary_

I should definitely update our dependencies though.

**Comment by hueniverse** [comment]
Activity doesn't mean anyone moving to v17 is going to want it...

**Comment by jedireza** [comment]
Sure thing. I'll look into v17 in more detail. It also looks like `glue` is going to get updated for v17 too, and using a manifest file with `glue` is the primary reason for `visionary`. But maybe things are so new that won't be a good pattern to continue using.

If we don't deprecate this module, I'm happy to bring it update to date.

**Comment by devinivy** [comment]
v17's `realm.parent` will affect how we think about this module.  It's possible the functionality could even be provided by vision.  Imagine if vision had `multiple` instead of `once` and could set the manager for the realm in which it is registered when options are provided.

**Comment by Danlock** [comment]
I use visionary to simplify my glue manifest configuration, like so. 
```
    {
      plugin: 'vision',
    },
    {
      plugin: {
        register: 'visionary',
        options: {
          engines: { hbs: 'handlebars' },
          path: relativeToRoot('public'),
        },
      },
    },
```

how would it look if it was builtin to vision?

**Comment by devinivy** [comment]
Would have to rope-in @wswoodruff, but I imagine that `realm.parent` would allow vision to make any plugin that does this,

```js
await server.register(Vision);
server.views({/* view manager options */});
```

to be able to do,

```js
await server.register({
    plugin: Vision,
    options: {/* view manager options */}
});
```

What I am not sure of is if vision is actually interested in this functionality, if it's considered beyond the scope of the package, or not worth the complexity.  But it might be an interesting option!  @jedireza from your perspective how does dropping `server.root` in hapi v17 affect visionary?

**Comment by jedireza** [comment]
> from your perspective how does dropping `server.root` in hapi v17 affect visionary?

@devinivy I'm unsure at this point. I need to understand more about the differences between [`server.realm`](https://hapijs.com/api/17.0.1#server.realm) and [`server.root`](https://hapijs.com/api/16.6.2#serverroot).

I intend to wait and see where `vision` lands. Deprecating unnecessary code is always good, let's hope that's possible with the updates in that module.

**Comment by wswoodruff** [comment]
@jedireza Glad to have your input! After speaking with @devinivy, here's my thinking -- open to feedback: I can see `vision` taking advantage of `realm.parent` by setting the manager on it during registration, and _if_ options are passed in, will call `.views()` on realm.parent for the user. If options are not passed in during registration, it would be up to the user to call `.views()`. That would allow the functionality Devin described in his comment

**Comment by wswoodruff** [comment]
Currently `pluginOptions` is unused in vision =P

**Comment by wswoodruff** [comment]
One use case for multiple registrations of `vision` would be (1) a module that manages template rendering for emails, (pass in the email templates path to that plugin) -- and (2) the website's template views -- they'd have different managers and the email module would register vision

**Comment by devinivy** [comment]
Vision is already designed to be registered multiple times– it should be registered by any plugin that needs it, which is the simplest way to manage a dependency on vision: register it yourself rather than relying on someone else to do it for you!

From my perspective, this change would add complexity to vision and perhaps complicate its API, since registration+options and `server.views(options)` would behave identically.  On the flip side, it would encompass the functionality of visionary, which I think otherwise would have to leverage what are currently vision internals in order to maintain its current functionality.  Tricky stuff!

**Comment by wswoodruff** [comment]
I have a PR for `multiple: true` in vision here: https://github.com/hapijs/vision/pull/135
Effectively, the only thing this adds is the ability to use 
```
await server.register({
    plugin: Vision,
    options: {/* view manager options */}
});
```
which will have the same effect as
```
await server.register(Vision);
server.views({/* view manager options */});
```

**Comment by travi** [comment]
i'm another `glue` user and am finally starting to try to get my `hapi` servers updated to v17. to clarify, is there currently a way to use `vision` with `glue` without `visionary`, or do some of the details above still need to be worked out before a server using `glue` and `vision` can be upgraded?

**Comment by wswoodruff** [comment]
@travi I'm still working on the PR mentioned above ☝️ to allow for vision to receive view manager options during registration (so it can work with glue)

So not right now but soon

**Comment by travi** [comment]
ok. thats what i thought i was understanding, but thank you for confirming. saves me from spinning my wheels before it is actually possible. if there is anything that help is need for to get this through, i'm happy to help out when i have time.

**Comment by wswoodruff** [comment]
@travi Vision `5.3.0` has passing manager options to register options

**Comment by jedireza** [comment]
@wswoodruff one thing I noticed with the latest version of `vision` is that it won't work for Glue users who's manifest is pure JSON. Here you can see in `visionary`, if the value of the engine key is a string, we require the module:

https://github.com/hapijs/visionary/blob/57638afed0a1c68272e6fe3166068ea57123b8b4/lib/index.js#L21

In my personal use cases with Glue, this won't be a problem since I don't have pure JSON manifest files, though adding support for this in `vision` may help some people be less dependent on `visionary`.

Thoughts?

**Comment by bts5** [comment]
Oh interesting @jedireza Yeah I think that sounds like a good idea, curious what the use-case is for having a JSON config, that can't be simple to change!

**Comment by hueniverse** [comment]
What's the verdict on this? Upgrade or deprecate?

**Comment by jedireza** [comment]
✋ deprecate
